"""empty message

Revision ID: 51b4145d41bb
Revises: 779f94ee11da
Create Date: 2022-07-26 03:00:04.761124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '51b4145d41bb'
down_revision = '779f94ee11da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'lastname',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'lastname',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
